### ISSUE TITLE
Changing the name of the project to be unique?

### ISSUE THREAD

**Issue by frastlin** [WhatSock/accdc-react#16]
Hello,
There is currently a project called [bootstrap-react](https://github.com/giridharangm/bootstrap-react.git)
on npm.
This means that if someone types:

`npm install bootstrap-react --save`

they will get that module.

I see two options:

1. Change the name to accdc-react
2. Create an [npm org](https://docs.npmjs.com/orgs/) and have a [scoped package](https://docs.npmjs.com/misc/scope) which would allow us to have `@accdc/bootstrap-react`

What would be prefered?

**Comment by accdc** [comment]
Probably the simplest thing is to rename the project to accdc-react.

Do you think this will require changing the GitHub reference url for the project as well?

**Comment by frastlin** [comment]
I've never changed the name of a project, so I'm not exactly sure.
How much of a problem would it be if the url changed? I personally get to this repo through emails or visiting my github profile.

I think that you could make the accdc org on npm and have your jquery, react, mootools, and all the other builds of accdc under your `@accdc` handle.
Then you can have bootstrap-jquery, and all the other names that you have come up with for the different builds.

**Comment by accdc** [comment]
I think this is now fixed. I changed all the names for both the project name and the GitHub referral and uploaded a new test build.

Hopefully this does the trick.

**Comment by frastlin** [comment]
Perfect! There may be some things that don't work with links, but we'll find those.
Thanks,
